;(function(){var dfltPluginCfg={};var dfltGlobalCfg={"site":"","log":"","logSSL":"","domain":"","secure":false,"pixelPath":"/hit.xiti","disableCookie":false,"cookieSecure":false,"cookieDomain":"","preview":false,"plgs":["Tracker","Campaigns","Clicks","ClientSideUserId","ContextVariables","Cookies","IdentifiedVisitor","InternalSearch","MvTesting","OnSiteAds","Page","SalesTracker","TechClicks","Utils","RichMedia"],"lazyLoadingPath":"","documentLevel":"document","redirect":false,"activateCallbacks":true,"medium":"","ignoreEmptyChapterValue":false,"base64Storage":false};(function(a,b){a.ATInternet=a.ATInternet||{};a.ATInternet.Tracker=a.ATInternet.Tracker||{};a.ATInternet.Tracker.Plugins=a.ATInternet.Tracker.Plugins||{}})(window);
window.ATInternet.Utils=new function(){function a(b){var l=typeof b;if("object"!==l||null===b)return"string"===l&&(b='"'+b+'"'),String(b);var k,g,d=[],c=b&&b.constructor===Array;for(k in b)b.hasOwnProperty(k)&&(g=b[k],l=typeof g,"function"!==l&&"undefined"!==l&&("string"===l?g='"'+g.replace(/[^\\]"/g,'\\"')+'"':"object"===l&&null!==g&&(g=a(g)),d.push((c?"":'"'+k+'":')+String(g))));return(c?"[":"{")+String(d)+(c?"]":"}")}var b=this;b.cloneSimpleObject=function l(a,b){if("object"!==typeof a||null===
a||a instanceof Date)return a;var d=new a.constructor||a.constructor(),c;for(c in a)a.hasOwnProperty(c)&&(void 0===c||b&&void 0===a[c]||(d[c]=l(a[c])));return d};b.jsonSerialize=function(l){return"undefined"!==typeof JSON&&JSON.stringify?JSON.stringify(l):a(l)};b.jsonParse=function(a){try{if("undefined"!==typeof JSON&&JSON.parse)return JSON.parse(a);var b;b=null===a?a:"string"===typeof a?(new Function("return "+a))():!1;return b}catch(g){return null}};b.arrayIndexOf=function(a,b){return Array.indexOf?
a.indexOf(b):function(a){if(null==this)throw new TypeError;var d=Object(this),c=d.length>>>0;if(0===c)return-1;var e=0;1<arguments.length&&(e=Number(arguments[1]),e!=e?e=0:0!=e&&Infinity!=e&&-Infinity!=e&&(e=(0<e||-1)*Math.floor(Math.abs(e))));if(e>=c)return-1;for(e=0<=e?e:Math.max(c-Math.abs(e),0);e<c;e++)if(e in d&&d[e]===a)return e;return-1}.apply(a,[b])};b.genGuid=function(a){var b=new Date,g=function(a){a-=100*Math.floor(a/100);return 10>a?"0"+a:a};return g(b.getHours())+""+g(b.getMinutes())+
""+g(b.getSeconds())+""+function(a){return Math.floor(Math.random()*Math.pow(10,a))}(a-6)};b.getObjectKeys=function(a){var b=[],g;for(g in a)a.hasOwnProperty(g)&&b.push(g);return b};b.completeFstLevelObj=function(a,b,g){if(a){if(b)for(var d in b)!b.hasOwnProperty(d)||a[d]&&!g||(a[d]=b[d])}else a=b;return a};b.isPreview=function(){return window.navigator&&"preview"===window.navigator.loadPurpose};b.isPrerender=function(a){var k,g=!1,d=["webkit","ms"];if("prerender"===document.visibilityState)k="visibilitychange";
else for(var c=0;c<d.length;c++)"prerender"===document[d[c]+"VisibilityState"]&&(k=d[c]+"visibilitychange");if("undefined"!==typeof k){var e=function(c){a(c);b.removeEvtListener(document,k,e)};b.addEvtListener(document,k,e);g=!0}return g};var h=b.addEvtListener=function(a,b,g){a.addEventListener?a.addEventListener(b,g,!1):a.attachEvent&&a.attachEvent("on"+b,g)};b.removeEvtListener=function(a,b,g){a.removeEventListener?a.removeEventListener(b,g,!1):a.detachEvent&&a.detachEvent("on"+b,g)};b.loadScript=
function(a,b){var g;b=b||function(){};g=document.createElement("script");g.type="text/javascript";g.src=a.url;g.async=!1;g.defer=!1;g.onload=g.onreadystatechange=function(a){a=a||window.event;if("load"===a.type||/loaded|complete/.test(g.readyState)&&(!document.documentMode||9>document.documentMode))g.onload=g.onreadystatechange=g.onerror=null,b(null,a)};g.onerror=function(a,d,l){g.onload=g.onreadystatechange=g.onerror=null;b({msg:"script not loaded",event:a})};var d=document.head||document.getElementsByTagName("head")[0];
d.insertBefore(g,d.lastChild)};b.hashcode=function(a){var b=0;if(0===a.length)return b;for(var g=0;g<a.length;g++)var d=a.charCodeAt(g),b=(b<<5)-b+d,b=b&b;return b};b.setLocation=function(a){var b=a.location;a=window[a.target]||window;b&&(a.location.href=b)};b.dispatchCallbackEvent=function(a){var b=document.createEvent("Event");b.initEvent("ATCallbackEvent",!0,!0);b.name=a;document.dispatchEvent(b)};b.addCallbackEvent=function(a){document.createEvent("Event").initEvent("ATCallbackEvent",!0,!0);h(document,
"ATCallbackEvent",a)}};
var BuildManager=function(a){var b=this,h=function(a,d,b){a="&"+a+"=";return{param:a,paramSize:a.length,str:d,strSize:d.length,truncate:b}},f=function(c,d){var b="",l=0,f=!0,r;for(r in c)if(c.hasOwnProperty(r)){var q=c[r];if(q){var f=!1,g=d-l;if(q.strSize+q.paramSize<g)b+=q.param+q.str,l+=q.strSize+q.paramSize,c[r]=void 0,f=!0;else{q.truncate?(b+=q.param+q.str.substr(0,g),c[r].str=q.str.substr(g,q.strSize-1),c[r].strSize=c[r].str.length):q.strSize+q.paramSize>d&&(a.emit("Tracker:Hit:Build:Error",{lvl:"ERROR",
msg:'Too long parameter "'+q.param+'"',details:{value:q.str}}),c[r].str=c[r].str.substr(0,d-q.paramSize-1),c[r].strSize=c[r].str.length);break}}else f=!0}return[b,f?null:c]},l=["ati","atc","pdtl","stc","dz"],k=function(c,d,b){var g=function(a){if(a==={})return"";var d=[],c;c={};var b=0,e=!1,g=void 0,r,n,k;for(k in a)if(a.hasOwnProperty(k)){var p=a[k].value;"function"===typeof p&&(p=p());p=p instanceof Array?p.join(a[k].options.separator||","):"object"===typeof p?window.ATInternet.Utils.jsonSerialize(p):
"undefined"===typeof p?"undefined":p.toString();a[k].options.encode&&(p=encodeURIComponent(p));var t=h(k,p,-1<window.ATInternet.Utils.arrayIndexOf(l,k)),b=b+(t.paramSize+t.strSize);if(a[k].options.last)1490<p.length&&p.substr(0,1490),r=k,n=t;else if(c[k]=t,1500<c[k].paramSize+c[k].strSize&&!c[k].truncate){e=!0;g=k;break}}r&&(c[r]=n);c=[c,b,e,g];a=c[0];if(c[2])c=c[3],a=a[c],a.str=a.str.substr(0,1450),a.strSize=1450,b={},b.mherr=h("mherr","1",!1),b[c]=a,d.push(f(b,1500)[0]);else if(c=f(a,1500),null===
c[1])d=c[0];else for(d.push(c[0]);null!==c[1];)c=f(a,1500),d.push(c[0]);return d},k="";a.buffer.presentInFilters(d,"hitType")||(d=a.buffer.addInFilters(d,"hitType",["page"]));d=a.buffer.addInFilters(d,"hitType",["all"]);var r;if(c){d=a.buffer.addInFilters(d,"permanent",!0);d=a.buffer.get(d,!0);for(r in c)c.hasOwnProperty(r)&&(d[r]={value:c[r],options:{}});k=g(d)}else for(r in d=a.buffer.get(d,!0),k=g(d),d)d.hasOwnProperty(r)&&!d[r].options.permanent&&a.buffer.del(r);b&&b(k)},g=function(c){var d=a.getConfig("secure"),
b="https:"===document.location.protocol,b=d||b?a.getConfig("logSSL"):a.getConfig("log"),l=a.getConfig("baseURL"),g=a.getConfig("domain"),r=a.getConfig("pixelPath"),q=a.getConfig("site");(l||b&&g&&r)&&q?c&&c(null,(l?l:(d?"https://":"//")+b+("."+g)+r)+("?s="+q)):c&&c({message:"Config error"})},d=function(a,d,b){g(function(l,g){l?b&&b(l):k(a,d,function(a){var d=[],c=window.ATInternet.Utils.genGuid(13);if(a instanceof Array)if(1===a.length)d.push(g+"&mh=1-2-"+c+a[0]);else for(var e=1;e<=a.length;e++)d.push(g+
"&mh="+e+"-"+a.length+"-"+c+a[e-1]);else d.push(g+a);b&&b(null,d)})})};b.send=function(c,e){d(c,e,function(d,c){if(d)a.emit("Tracker:Hit:Build:Error",{lvl:"ERROR",msg:d.message,details:{hits:c}});else for(var e=0;e<c.length;e++)b.sendUrl(c[e])})};b.sendUrl=function(d){var b=function(d,c){return function(){return function(b){a.emit(d,{lvl:-1===d.indexOf("Error")?"INFO":"ERROR",details:{hit:c,event:b}})}}()},l=new Image;l.onload=b("Tracker:Hit:Sent:Ok",d);l.onerror=b("Tracker:Hit:Sent:Error",d);l.src=
d}},TriggersManager=function(){function a(a,b,g){for(var d=[],c=0;c<a.length;c++)a[c].callback(b,g),a[c].singleUse||d.push(a[c]);return d}function b(a,f,g,d){var c=a.shift();if("*"===c)return f["*"]=f["*"]||[],f["*"].push({callback:g,singleUse:d}),f["*"].length-1;if(0===a.length)return b([c,"*"],f,g,d);f["*"]=f["*"]||[];f[c]=f[c]||{};return b(a,f[c],g,d)}function h(b,f,g,d){var c=f.shift();"*"!==c&&(0===f.length?h(b,[c,"*"],g,d):g[c]&&(g[c]["*"]=a(g[c]["*"],b,d),h(b,f,g[c],d)))}var f={};this.on=function(a,
k,g){g=g||!1;return b(a.split(":"),f,k,g)};this.emit=function(b,k){f["*"]&&(f["*"]=a(f["*"],b,k));h(b,b.split(":"),f,k)}},PluginsManager=function(a){var b={},h={},f=0,l={},k=0,g=this.load=function(c,e){"function"===typeof e?"undefined"===typeof a.getConfig.plgAllowed||0===a.getConfig.plgAllowed.length||-1<a.getConfig.plgAllowed.indexOf(c)?(b[c]=new e(a),h[c]&&b[c]&&(h[c]=!1,f--,b[c+"_ll"]&&d(c+"_ll"),0===f&&a.emit("Tracker:Plugin:Lazyload:File:Complete",{lvl:"INFO",msg:"LazyLoading triggers are finished"})),
a.emit("Tracker:Plugin:Load:"+c+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Load:"+c+":Error",{lvl:"ERROR",msg:"Plugin not allowed",details:{}}):a.emit("Tracker:Plugin:Load:"+c+":Error",{lvl:"ERROR",msg:"not a function",details:{obj:e}});return a},d=this.unload=function(d){b[d]?(b[d]=void 0,a.emit("Tracker:Plugin:Unload:"+d+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Unload:"+d+":Error",{lvl:"ERROR",msg:"not a known plugin"});return a},c=this.isLazyloading=function(a){return a?!0===h[a]:0!==f},e=
function(a){return p(a)?(n(a),!0):!1},n=function(d){h[d]=!0;f++;ATInternet.Utils.loadScript({url:a.getConfig("lazyLoadingPath")+d+".js"})},p=function(a){return!b[a]&&!c(a)&&(b[a+"_ll"]?!0:!1)},t=function(a){l[a]?l[a]++:l[a]=1;k++};this.isExecWaitingLazyloading=function(){return 0!==k};a.exec=this.exec=function(d,e,f,g){var h=null,s=function(a,d,c,e){d=d.split(".");b[a]&&b[a][d[0]]&&(h=1<d.length&&b[a][d[0]][d[1]]?b[a][d[0]][d[1]].apply(b[a],c):b[a][d[0]].apply(b[a],c));e&&e(h)},u=function(d,c,b,e){t(d);
a.onTrigger("Tracker:Plugin:Load:"+d+":Ok",function(){s(d,c,b,function(c){l[d]--;k--;0===k&&a.emit("Tracker:Plugin:Lazyload:Exec:Complete",{lvl:"INFO",msg:"All exec waiting for lazyloading are done"});e&&e(c)})},!0)};p(d)?(u(d,e,f,g),n(d)):c(d)?u(d,e,f,g):s(d,e,f,g)};this.waitForDependencies=function(d,c){var f=function(a){for(var d={mcount:0,plugins:{}},c=0;c<a.length;c++)b.hasOwnProperty(a[c])||(d.mcount++,d.plugins[a[c]]=!0);return d}(d);if(0===f.mcount)a.emit("Tracker:Plugin:Dependencies:Loaded",
{lvl:"INFO",details:{dependencies:d}}),c();else for(var g in f.plugins)f.plugins.hasOwnProperty(g)&&(a.emit("Tracker:Plugin:Dependencies:Error",{lvl:"WARNING",msg:"Missing plugin "+g}),a.onTrigger("Tracker:Plugin:Load:"+g,function(a,d){var b=a.split(":"),e=b[3];"Ok"===b[4]&&(f.plugins[e]=!1,f.mcount--,0===f.mcount&&c())},!0),e(g))};this.init=function(){for(var a in ATInternet.Tracker.pluginProtos)ATInternet.Tracker.pluginProtos.hasOwnProperty(a)&&g(a,ATInternet.Tracker.pluginProtos[a])}},CallbacksManager=
function(a){var b={};this.init=function(){if(a.getConfig("activateCallbacks")){var f=a.getConfig("callbacks");(function(){if("undefined"!==typeof f&&f.include instanceof Array)for(var a=0;a<f.include.length;a++)ATInternet.Callbacks&&ATInternet.Callbacks.hasOwnProperty(f.include[a])&&(b[f.include[a]]={"function":ATInternet.Callbacks[f.include[a]]},ATInternet.Tracker.callbackProtos[f.include[a]]||(ATInternet.Tracker.callbackProtos[f.include[a]]=b[f.include[a]]));else for(a in ATInternet.Callbacks)ATInternet.Callbacks.hasOwnProperty(a)&&
(b[a]={"function":ATInternet.Callbacks[a]},ATInternet.Tracker.callbackProtos[a]||(ATInternet.Tracker.callbackProtos[a]=b[a]));if("undefined"!==typeof f&&f.exclude instanceof Array)for(a=0;a<f.exclude.length;a++)b[f.exclude[a]]&&(b[f.exclude[a]]=void 0);for(var k in b)b.hasOwnProperty(k)&&b[k]&&h(k,b[k]["function"])})();ATInternet.Utils.addCallbackEvent(function(a){if(a.name){var b=!0;"undefined"!==typeof f&&(f.include instanceof Array&&-1===ATInternet.Utils.arrayIndexOf(f.include,a.name)&&(b=!1),
f.exclude instanceof Array&&-1!==ATInternet.Utils.arrayIndexOf(f.exclude,a.name)&&(b=!1));if(ATInternet.Callbacks&&ATInternet.Callbacks.hasOwnProperty(a.name)){var g={};g[a.name]={"function":ATInternet.Callbacks[a.name]};b&&h(a.name,g[a.name]["function"]);ATInternet.Tracker.callbackProtos[a.name]||(ATInternet.Tracker.callbackProtos[a.name]=g[a.name])}}})}};var h=this.load=function(b,l){"function"===typeof l?(new l(a),a.emit("Tracker:Callback:Load:"+b+":Ok",{lvl:"INFO",details:{obj:l}})):a.emit("Tracker:Callback:Load:"+
b+":Error",{lvl:"ERROR",msg:"not a function",details:{obj:l}});return a}},BufferManager=function(a){var b={};this.set=function(f,k,g){g=g||{};g.hitType=g.hitType||["page"];b[f]={value:k,options:g};a.debug("Tracker:Buffer:setParam","DEBUG","",{name:f,value:k,options:g,buffer:b})};var h=function(a,b,f){return(a=window.ATInternet.Utils.cloneSimpleObject(a[b]))&&!f?a.value:a},f=function k(a,d){if(!(a&&d instanceof Array&&a instanceof Array))return[];if(0===a.length)return d;var c=a[0],e,f=[],h=window.ATInternet.Utils.cloneSimpleObject(a);
h.shift();for(var t=0;t<d.length;t++)if("object"!==typeof c[1])b[d[t]]&&b[d[t]].options[c[0]]===c[1]&&f.push(d[t]);else{e=c[1].length;for(var r=0;r<e;r++)if(b[d[t]]&&b[d[t]].options[c[0]]instanceof Array&&0<=window.ATInternet.Utils.arrayIndexOf(b[d[t]].options[c[0]],c[1][r])){f.push(d[t]);break}}return k(h,f)};this.get=function(a,g){var d={};if("string"===typeof a)d=h(b,a,g);else for(var c=f(a,window.ATInternet.Utils.getObjectKeys(b)),e=0;e<c.length;e++)d[c[e]]=h(b,c[e],g);return d};this.presentInFilters=
function g(a,c){return a&&0!==a.length?a[0][0]===c?!0:g(a.slice(1),c):!1};this.addInFilters=function d(a,b,f,h){if(!a||0===a.length)return h?[]:[[b,f]];var t=a[0][0],r=a[0][1];t===b&&(r instanceof Array&&!(-1<window.ATInternet.Utils.arrayIndexOf(r,f[0]))&&r.push(f[0]),h=!0);return[[t,r]].concat(d(a.slice(1),b,f,h))};this.del=function(d){b[d]=void 0;a.debug("Tracker:Buffer:delParam","DEBUG","",{name:d,buffer:b})};this.clear=function(){b={}}},Tag=function(a,b,h){b=b||{};var f=this;f.version="5.6.0";
var l=window.ATInternet.Utils.cloneSimpleObject(b);f.triggers=new TriggersManager(f);f.emit=f.triggers.emit;f.debug=function(a,c,b,g){f.emit(a,{lvl:c,msg:b,details:g})};f.onTrigger=f.triggers.on;var k=window.ATInternet.Utils.cloneSimpleObject(dfltGlobalCfg)||{},g;for(g in a)a.hasOwnProperty(g)&&(k[g]=a[g]);f.getConfig=function(a){return k[a]};f.setConfig=function(a,c,b){void 0!==k[a]&&b||(f.emit("Tracker:Config:Set:"+a,{lvl:"INFO",details:{bef:k[a],aft:c}}),k[a]=c)};f.configPlugin=function(a,c,b){k[a]=
k[a]||{};for(var g in c)c.hasOwnProperty(g)&&void 0===k[a][g]&&(k[a][g]=c[g]);b&&(b(k[a]),f.onTrigger("Tracker:Config:Set:"+a,function(a,d){b(d.details.aft)}));return k[a]};f.getContext=function(a){return l[a]};f.setContext=function(a,c){f.emit("Tracker:Context:Set:"+a,{lvl:"INFO",details:{bef:l[a],aft:c}});l[a]=c};f.delContext=function(a,c){f.emit("Tracker:Context:Deleted:"+a+":"+c,{lvl:"INFO",details:{key1:a,key2:c}});if(a)l.hasOwnProperty(a)&&(c?l[a]&&l[a].hasOwnProperty(c)&&(l[a][c]=void 0):l[a]=
void 0);else if(c)for(var b in l)l.hasOwnProperty(b)&&l[b]&&l[b].hasOwnProperty(c)&&(l[b][c]=void 0)};f.plugins=new PluginsManager(f);f.buffer=new BufferManager(f);f.setParam=f.buffer.set;f.getParams=function(a){return f.buffer.get(a,!1)};f.getParam=f.buffer.get;f.delParam=f.buffer.del;f.builder=new BuildManager(f);f.sendHit=f.builder.send;f.sendUrl=f.builder.sendUrl;f.callbacks=new CallbacksManager(f);f.setParam("ts",function(){return(new Date).getTime()},{permanent:!0,hitType:["all"]});f.getConfig("disableCookie")&&
f.setParam("idclient","xxxxxx-NO",{permanent:!0,hitType:["all"]});f.getConfig("medium")&&f.setParam("medium",f.getConfig("medium"),{permanent:!0,hitType:["all"]});f.plugins.init();f.callbacks.init();ATInternet.Tracker.instances.push(f);f.emit("Tracker:Ready",{lvl:"INFO",msg:"Tracker initialized",details:{tracker:f,args:{config:a,context:b,callback:h}}});h&&h(f)};ATInternet.Tracker.Tag=Tag;ATInternet.Tracker.instances=[];ATInternet.Tracker.pluginProtos={};
ATInternet.Tracker.addPlugin=function(a,b){b=b||ATInternet.Tracker.Plugins[a];if(!ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=b;for(var h=0;h<ATInternet.Tracker.instances.length;h++)ATInternet.Tracker.instances[h].plugins.load(a,b)}};ATInternet.Tracker.delPlugin=function(a){if(ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=void 0;for(var b=0;b<ATInternet.Tracker.instances.length;b++)ATInternet.Tracker.instances[b].plugins.unload(a)}};
ATInternet.Tracker.callbackProtos={};
}).call(window);;(function(){var dfltPluginCfg={"lifetime":30,"lastPersistence":true,"listEventsForExec":[],"domainAttribution":true};var dfltGlobalCfg={"visitLifetime":30,"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.Campaigns=function(a){a.setConfig("visitLifetime",dfltGlobalCfg.visitLifetime,!0);a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var b={},h,f;a.configPlugin("Campaigns",dfltPluginCfg||{},function(a){b=a});var l,k,g,d,c,e,n,p,t,r,q,v,y,A=function(c,b,d){var e=null;a.plugins.exec(c,b,d,function(a){e=a});return e},s=function(a,c){return A("Cookies",a,c)},u=function(a,c){return A("Utils",a,c)},C=function(a,c){var b=s(f,[[a]]);if(null!==b)return!("object"!==
typeof b||b instanceof Array);s(h,[a,{},c]);return!0},N=function(c,b){var d=a.getContext("campaigns")||{};d[c]=b;a.setContext("campaigns",d)},w=function(A){h="set"+(b.domainAttribution?"":"Private");f="get"+(b.domainAttribution?"":"Private");l=s(f,[["atredir","gopc"]]);k=s(f,[["atredir","gopc_err"]]);g=s(f,[["atredir","camp"]]);s("del",[["atredir","gopc"]]);s("del",[["atredir","gopc_err"]]);s("del",[["atredir","camp"]]);d=s(f,[["atsession","histo_camp"]]);c=s(f,[["atreman","camp"]]);e=s(f,[["atreman",
"date"]]);var w=u("getLocation",[]);n=u("getQueryStringValue",["xtor",w]);p=u("getQueryStringValue",["xtdt",w]);t=u("getQueryStringValue",["xts",w]);r=a.getContext("forcedCampaign");q=!!a.getConfig("redirect");if(v=n&&p&&t?!0:!1)w=(new Date).getTime()/6E4,y=!q&&t!==a.getConfig("site")||0>w-p||w-p>=a.getConfig("visitLifetime")?!0:!1;w=r||g||n;q&&w&&C("atredir",{path:"/",end:a.getConfig("redirectionLifetime")})&&(s(h,[["atredir","camp"],w]),s(h,[["atredir","gopc"],r?!1:g?l:v?!0:!1]),s(h,[["atredir",
"gopc_err"],r?!1:g?k:y?!0:!1]));!q&&c&&(N("xtor",c),w=(new Date).getTime()/36E5,w=Math.floor(w-e),N("roinbh",0<=w?w:0));q||(w=void 0,w=g?l?r||w:r||g:v?r||w:r||n||w,d&&d instanceof Array&&-1<d.indexOf(w)&&(w=void 0),w&&N("xto",w));if(!q&&!r){var J;g?k&&(J=g):y&&(J=n);J&&N("pgt",J)}q||!(J=g?r||g:r||n||void 0)||!r&&!g&&v&&y||!r&&g&&l&&k||((!d||d instanceof Array&&0>d.indexOf(J))&&C("atsession",{path:"/",session:60*a.getConfig("visitLifetime")})&&s(h,[["atsession","histo_camp"],d&&d.push(J)?d:[J]]),c&&
!b.lastPersistence||!C("atreman",{path:"/",session:86400*b.lifetime})||(s(h,[["atreman","camp"],J]),s(h,[["atreman","date"],(new Date).getTime()/36E5])));a.emit("Campaigns:"+A,{lvl:"INFO"})};(function(){var c=["Cookies","Utils"];if(-1===ATInternet.Utils.arrayIndexOf(a.getConfig("plgs"),"BackwardCompat"))a.plugins.waitForDependencies(c,function(){w("process2:done")});else a.onTrigger("BackCampaigns:process2:done",function(b,d){a.plugins.waitForDependencies(c,function(){w("process1:done")})},!0)})()};
window.ATInternet.Tracker.addPlugin("Campaigns");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Clicks=function(a){var b=function(a){var b="";switch(a){case "exit":b="S";break;case "download":b="T";break;case "action":b="A";break;case "navigation":b="N"}return b},h=function(b){var f=b.name;a.exec("Utils","manageChapters",[b,"chapter",3],function(a){f=a+(f?f:"")});return f},f=function(f){var k={p:h(f),s2:f.level2||"",click:b(f.type)||""},g=a.getContext("page")||{};k.pclick=h(g);k.s2click=g.level2||"";f.customObject&&a.exec("Utils","customObjectToString",[f.customObject],
function(a){k.stc=a});a.sendHit(k,[["hitType",["click"]]])};a.click={};a.clickListener=this.clickListener={};a.click.send=this.send=function(b){var k=!0;a.plugins.exec("TechClicks","manageClick",[b.elem],function(a){k=a});f(b);a.debug("Clicks:click:send","DEBUG","method ended",b);return k};a.clickListener.send=this.clickListener.send=function(b){if(b.elem){var k;a.plugins.exec("TechClicks","isFormSubmit",[b.elem],function(a){k=a?"submit":"click"});ATInternet.Utils.addEvtListener(b.elem,k,function(g){a.plugins.exec("TechClicks",
"manageClick",[b.elem,g]);f(b)})}a.debug("Clicks:clickListener:send","DEBUG","method ended",b)};a.click.set=this.set=function(f){a.dispatchSubscribe("click");a.setContext("click",{name:h(f),level2:f.level2||"",customObject:f.customObject});a.setParam("click",b(f.type)||"",{hitType:["click"]});a.debug("Clicks:click:set","DEBUG","method ended",f)};a.click.onDispatch=this.onDispatch=function(){var b={hitType:["click"]};a.setParam("p",a.getContext("click").name,b);a.setParam("s2",a.getContext("click").level2,
b);var f=a.getContext("click").customObject;f&&a.setParam("stc",f,{hitType:["click"],encode:!0});f=a.getContext("page")||{};a.setParam("pclick",h(f),b);a.setParam("s2click",f.level2||"",b);a.sendHit(null,[["hitType",["click"]]]);a.setContext("click",void 0)}};window.ATInternet.Tracker.addPlugin("Clicks");
}).call(window);;(function(){var dfltPluginCfg={"clientSideMode":"required","userIdCookieDuration":397,"userIdExpirationMode":"fixed"};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.ClientSideUserId=function(a){var b={},h=void 0,f=null;a.configPlugin("ClientSideUserId",dfltPluginCfg||{},function(a){b=a});var l=function(){h=a.getContext("userIdentifier");a.exec("Cookies","get",["atuserid"],function(a){f=a})},k=function(c,b){a.setParam("idclient",c,{permanent:!0,hitType:["all"]});g(c,b)},g=function(c,d){if("relative"===b.userIdExpirationMode||"fixed"===b.userIdExpirationMode&&null===f){var g=new Date;g.setTime(g.getTime()+864E5*b.userIdCookieDuration);
a.exec("Cookies","set",["atuserid",c,{end:g,path:"/"}]);a.exec("Cookies","get",["atuserid",!0],function(b){d||c===b||a.setParam("idclient",c+"-NO",{permanent:!0,hitType:["all"]})})}},d=function(){var a=!1;if("required"===b.clientSideMode){var d=navigator.userAgent;if(/Safari/.test(d)&&!/Chrome/.test(d)||/iPhone|iPod|iPad/.test(d))a=!0}else"always"===b.clientSideMode&&(a=!0);return a};a.plugins.waitForDependencies(["Cookies"],function(){l();var c="";if(d()){var e=!1;"undefined"!==typeof h?(c=h,e=!0):
c=null!==f?f:ATInternet.Utils.genGuid(13);k(c,e)}a.emit("ClientSideUserId:Ready",{lvl:"INFO",details:{clientSideMode:b.clientSideMode,userIdFromContext:h,userIdFromCookie:f,userId:c}})});a.clientSideUserId={};a.clientSideUserId.set=function(c){d()&&k(c,!0);a.debug("ClientSideUserId:clientSideUserId:set","DEBUG","method ended",{id:c})}};window.ATInternet.Tracker.addPlugin("ClientSideUserId");
}).call(window);;(function(){var dfltPluginCfg={"domainAttribution":true};var dfltGlobalCfg={"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.ContextVariables=function(a){var b="",h=null,f="",l="",k={};a.configPlugin("ContextVariables",dfltPluginCfg||{},function(a){k=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var g=function(c,b,d){var e=null;a.plugins.exec(c,b,d,function(a){e=a});return e},d=function(a,c){return g("Utils",a,c)},c=function(c,b){var d=null;a.plugins.exec("Cookies",c,b,function(a){d=a});return d},e=function(){a.setParam("hl",function(){var a=new Date;return a.getHours()+
"x"+a.getMinutes()+"x"+a.getSeconds()},{permanent:!0,hitType:["all"]})},n=function(a){var c="",c="acc_dir"===b?"":b?b:"acc_dir"===h?"":h?h:a.referrer;return c.replace(/[<>]/g,"").substring(0,1600).replace(/&/g,"$")};a.plugins.waitForDependencies(["Cookies","Utils"],function(){f="set"+(k.domainAttribution?"":"Private");l="get"+(k.domainAttribution?"":"Private");var g=d("getLocation",[]);b=d("getQueryStringValue",["xtref",g]);if(a.getConfig("redirect")){var g=d("getDocumentLevel",[]),g=b||g.referrer||
"acc_dir",t;if(t=g){t={path:"/",end:a.getConfig("redirectionLifetime")};var r=c(l,[["atredir"]]);null!==r?t=!("object"!==typeof r||r instanceof Array):(c(f,["atredir",{},t]),t=!0)}t&&c(f,[["atredir","ref"],g])}else{h=c(l,[["atredir","ref"]]);c("del",[["atredir","ref"]]);a.setParam("vtag",a.version,{permanent:!0,hitType:["all"]});a.setParam("ptag","js",{permanent:!0,hitType:["all"]});g="";try{g+=window.screen.width+"x"+window.screen.height+"x"+window.screen.pixelDepth+"x"+window.screen.colorDepth}catch(q){a.debug("ContextVariables:ScreenResolution",
"ERROR","Screen resolution exception",{except:q})}a.setParam("r",g,{permanent:!0,hitType:["all"]});g="";window.innerWidth?g+=window.innerWidth+"x"+window.innerHeight:document.body.offsetWidth&&(g+=document.body.offsetWidth+"x"+document.body.offsetHeight);a.setParam("re",g,{permanent:!0,hitType:["all"]});e();a.setParam("lng",navigator.language||navigator.userLanguage,{permanent:!0,hitType:["all"]});g=window.ATInternet.Utils.genGuid(13);a.setParam("idp",g,{permanent:!0,hitType:["page","clickzone"]});
a.setParam("jv",navigator.javaEnabled()?"1":"0",{hitType:["page"]});g=d("getDocumentLevel",[]);a.setParam("ref",n(g),{permanent:!0,last:!0,hitType:["page"]})}a.emit("ContextVariables:Ready",{lvl:"INFO"})})};window.ATInternet.Tracker.addPlugin("ContextVariables");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Cookies=function(a){var b={},h={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var c="",b,d,e,g,f,n,k=0;for(a=h._utf8_encode(a);k<a.length;)b=a.charCodeAt(k++),d=a.charCodeAt(k++),e=a.charCodeAt(k++),g=b>>2,b=(b&3)<<4|d>>4,f=(d&15)<<2|e>>6,n=e&63,isNaN(d)?f=n=64:isNaN(e)&&(n=64),c=c+this._keyStr.charAt(g)+this._keyStr.charAt(b)+this._keyStr.charAt(f)+this._keyStr.charAt(n);return c},decode:function(a){var c="",b,d,e,
g,f,n=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");n<a.length;)b=this._keyStr.indexOf(a.charAt(n++)),d=this._keyStr.indexOf(a.charAt(n++)),g=this._keyStr.indexOf(a.charAt(n++)),f=this._keyStr.indexOf(a.charAt(n++)),b=b<<2|d>>4,d=(d&15)<<4|g>>2,e=(g&3)<<6|f,c+=String.fromCharCode(b),64!=g&&(c+=String.fromCharCode(d)),64!=f&&(c+=String.fromCharCode(e));return c=h._utf8_decode(c)},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var c="",b=0;b<a.length;b++){var d=a.charCodeAt(b);128>d?c+=String.fromCharCode(d):
(127<d&&2048>d?c+=String.fromCharCode(d>>6|192):(c+=String.fromCharCode(d>>12|224),c+=String.fromCharCode(d>>6&63|128)),c+=String.fromCharCode(d&63|128))}return c},_utf8_decode:function(a){for(var c="",b=0,d,e,g;b<a.length;)d=a.charCodeAt(b),128>d?(c+=String.fromCharCode(d),b++):191<d&&224>d?(e=a.charCodeAt(b+1),c+=String.fromCharCode((d&31)<<6|e&63),b+=2):(e=a.charCodeAt(b+1),g=a.charCodeAt(b+2),c+=String.fromCharCode((d&15)<<12|(e&63)<<6|g&63),b+=3);return c}},f=this.getCookie=function(c){return!a.getConfig("disableCookie")&&
c&&"string"===typeof c&&(a.debug("Cookies:ReadCookie:FromBrowser","DEBUG","",{name:c}),c=RegExp("(?:^| )"+c+"=([^;]+)").exec(document.cookie)||null)?(c=c[1],c=a.getConfig("base64Storage")?h.decode(c):decodeURIComponent(c),c):null},l=this.setCookie=function(c,b,d){if(!a.getConfig("disableCookie")&&c&&"string"===typeof c&&"string"===typeof b){a.debug("Cookies:SetCookie","DEBUG","",{name:c,value:b,options:d});var e=a.getConfig("cookieDomain");c+="=";b=a.getConfig("base64Storage")?h.encode(b):encodeURIComponent(b);
b=c+b;c=!1;if(d){c=d.secure;var g=d.end,f=d.domain;d=d.path;b+=g?"function"===typeof g.toGMTString?";expires="+g.toGMTString():"number"===typeof g?";max-age="+g.toString():"":"";b=b+(e||f?";domain="+(f?f:e):"")+(d&&"string"===typeof d?";path="+d:"")}e=a.getConfig("cookieSecure")||c;b+=e&&"boolean"===typeof e?";secure":"";document.cookie=b;return!0}return null},k=function(a){var c=null;(a=f(a))&&(c=ATInternet.Utils.jsonParse(a));return c},g=function(a){return l(a.name,ATInternet.Utils.jsonSerialize(a),
a.options)?a:null},d=function(c,d,e){var f=null;if(!e&&b[c])f=b[c],a.debug("Cookies:ReadCookie:FromCache","DEBUG","",{name:c,cache:b});else if(f=k(c))f.options.session&&g(f),b[c]=f;return f?d?(c=null,!f||"object"!==typeof f.val||f.val instanceof Array||void 0===f.val[d]||(c=f.val[d]),c):f.val:null},c=function(a,c,d,e){var f=null;if(c){if(f=k(a))e=f,!e||"object"!==typeof e.val||e.val instanceof Array?f=null:(e.val[c]=d,f=e),f&&(f=g(f))}else c=e=e||{},e={},e.name=a,e.val=d,c.session&&"number"===typeof c.session&&
(c.end=c.session),e.options=c,f=g(e);f&&(b[a]=f);return f?f.val:null},e=function(a,d){d?c(a,d,void 0):(b[a]=void 0,l(a,"",{end:0}))},n=this.get=function(a,c){c=c||!1;return a instanceof Array&&2===a.length?d(a[0],a[1],c):d(a,void 0,c)};this.getPrivate=function(c,b){b=b||!1;c instanceof Array?c[0]+=a.getConfig("site"):c+=a.getConfig("site");return n(c,b)};var p=this.set=function(a,b,d){return a instanceof Array?c(a[0],a[1],b):c(a,null,b,d)};this.setPrivate=function(c,b,d){c instanceof Array?c[0]+=
a.getConfig("site"):c+=a.getConfig("site");return p(c,b,d)};var t=this.del=function(a){return a instanceof Array?e(a[0],a[1]):e(a)};this.delPrivate=function(c){c instanceof Array?c[0]+=a.getConfig("site"):c+=a.getConfig("site");return t(c)};this.cacheInvalidation=function(){a.debug("Cookies:ClearCache","DEBUG","");b={}}};window.ATInternet.Tracker.addPlugin("Cookies");
}).call(window);;(function(){var dfltPluginCfg={"lifetime":182,"domainAttribution":true};var dfltGlobalCfg={"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.IdentifiedVisitor=function(a){var b=null,h=null,f=null,l=null,k="",g="",d=null,c=null,e="",n="",p={};a.configPlugin("IdentifiedVisitor",dfltPluginCfg||{},function(a){p=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var t=function(c,b,d){var e=null;a.plugins.exec(c,b,d,function(a){e=a});return e},r=function(a,c){return t("Utils",a,c)},q=function(c,b){var d=null;a.plugins.exec("Cookies",c,b,function(a){d=a});return d},v=function(a,c){var b=
q(n,[[a]]);if(null!==b)return!("object"!==typeof b||b instanceof Array);q(e,[a,{},c]);return!0},y=function(){var e=function(a,c){/-/.test(c)?(a.category=c.split("-")[0],a.id=c.split("-")[1]):a.id=c},n={category:"",id:""};e(n,g||c);var l={category:"",id:""};e(l,k||d);l.id?(l.category&&s("ac",l.category),s("at",l.id)):b&&a.setParam("at",b,{hitType:["all"],permanent:!0});n.id?(n.category&&s("ac",n.category),s("an",n.id)):h&&a.setParam("anc",f+"-"+h,{hitType:["all"],permanent:!0})},A=function(a,c){v("atidvisitor",
{path:"/",session:86400*p.lifetime})&&q(e,[["atidvisitor",a],c])},s=function(c,b){a.setParam(c,b,{hitType:["all"],permanent:!0});A(c,b)};a.plugins.waitForDependencies(["Cookies","Utils"],function(){e="set"+(p.domainAttribution?"":"Private");n="get"+(p.domainAttribution?"":"Private");var u=r("getLocation",[]);k=r("getQueryStringValue",["xtat",u]);g=r("getQueryStringValue",["xtan",u]);a.getConfig("redirect")?(k||g)&&v("atredir",{path:"/",end:a.getConfig("redirectionLifetime")})&&(g&&q(e,[["atredir",
"an"],g]),k&&q(e,[["atredir","at"],k])):(d=q(n,[["atredir","at"]]),c=q(n,[["atredir","an"]]),q("del",[["atredir","at"]]),q("del",[["atredir","an"]]),b=q(n,[["atidvisitor","at"]]),h=q(n,[["atidvisitor","an"]]),f=q(n,[["atidvisitor","ac"]]),l=q(n,[["atidvisitor","vrn"]]),y(),u="-"+a.getConfig("site")+"-",RegExp(u).test(l)||(l=(l||"")+u,A("vrn",l),u=a.getContext("page")||{},u.vrn=1,a.setContext("page",u)));a.emit("IdentifiedVisitor:Ready",{lvl:"INFO",details:{cookieRedirectTextual:d,cookieRedirectNumeric:c,
cookieTextual:b,cookieNumeric:h,cookieCategory:f,cookieVrn:l}})});a.identifiedVisitor={};a.identifiedVisitor.set=this.set=function(c){var b=c.id,d=c.category;"number"===typeof b?s("an",b.toString()):s("at",b);"undefined"!==typeof d&&s("ac",d);a.debug("IdentifiedVisitor:identifiedVisitor:set","DEBUG","method ended",c)};a.identifiedVisitor.unset=this.unset=function(){for(var c=["an","at","ac"],b=0;b<c.length;b++)a.exec("Cookies","set",[["atidvisitor",c[b],{path:"/"}],void 0]),a.delParam(c[b]);a.delParam("anc");
a.debug("IdentifiedVisitor:identifiedVisitor:unset","DEBUG","method ended")}};window.ATInternet.Tracker.addPlugin("IdentifiedVisitor");
}).call(window);;(function(){var dfltPluginCfg={"urlKeyword":"","urlResultPageNumber":"","urlResultPosition":""};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.InternalSearch=function(a){var b={};a.configPlugin("InternalSearch",dfltPluginCfg||{},function(a){b=a});var h=function(b){var h={np:"undefined"!==typeof b.resultPageNumber?b.resultPageNumber:"1",click:"IS"};b.hasOwnProperty("keyword")&&(h.mc=b.keyword);b.hasOwnProperty("resultPosition")&&(h.mcrg=b.resultPosition);a.sendHit(h,[["hitType",["InternalSearch"]]])};a.internalSearch={};a.internalSearch.set=this.set=function(b){var h={},k=h;b.hasOwnProperty("keyword")&&(k.keyword=
b.keyword);k=h;b.hasOwnProperty("resultPageNumber")&&(k.resultPageNumber=b.resultPageNumber);k=a.getContext("InternalSearch")||{};h=ATInternet.Utils.completeFstLevelObj(h,k);"undefined"===typeof h.resultPageNumber&&(h.resultPageNumber="1");a.setContext("InternalSearch",h);a.debug("InternalSearch:internalSearch:set","DEBUG","method ended",b)};a.internalSearch.send=this.send=function(b){var l=!0;a.plugins.exec("TechClicks","manageClick",[b.elem],function(a){l=a});h(b);a.debug("InternalSearch:internalSearch:send",
"DEBUG","method ended",b);return l};a.plugins.waitForDependencies(["Utils"],function(){var f;if(b.urlKeyword){var h=document.location.href;f={};a.plugins.exec("Utils","getQueryStringValue",[b.urlKeyword,h],function(k){k&&(f.keyword=k);b.urlResultPageNumber&&a.plugins.exec("Utils","getQueryStringValue",[b.urlResultPageNumber,h],function(a){f.resultPageNumber=a||"1"})})}f&&a.setContext("InternalSearch",f);a.emit("InternalSearch:Ready",{lvl:"INFO",details:{config:{urlKeyword:b.urlKeyword,urlResultPageNumber:b.urlResultPageNumber},
url:h,data:f}})})};window.ATInternet.Tracker.addPlugin("InternalSearch");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.MvTesting=function(a){var b=0,h=function(a,b){var c="";a.hasOwnProperty(b)&&(c=a[b],c=void 0===c?"":c+"");return c},f=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},l=function(a){return"object"===typeof a&&!(a instanceof Array)},k=function(b){var d=b.name;a.exec("Utils","manageChapters",[b,"chapter",3],function(a){d=a+(d?d:"")});return d};a.mvTesting={};a.mvTesting.set=function(b){if(l(b)&&!f(b)){a.dispatchSubscribe("mvTesting");var d=h(b,"test"),
c=h(b,"waveId"),e=h(b,"creation");a.setParam("abmvc",d+"-"+c+"-"+e,{hitType:["mvtesting"]})}a.debug("MvTesting:mvTesting:set","DEBUG","method ended",b)};a.mvTesting.add=function(g){if(l(g)&&!f(g)){a.dispatchSubscribe("mvTesting");var d=h(g,"variable"),c=h(g,"version");b++;a.setParam("abmv"+b,d+"-"+c,{hitType:["mvtesting"]})}a.debug("MvTesting:mvTesting:add","DEBUG","method ended",g)};a.mvTesting.onDispatch=function(){var b=a.getContext("page")||{};a.setParam("p",k(b),{hitType:["mvtesting"]});a.setParam("s2",
b.level2||"",{hitType:["mvtesting"]});a.setParam("type","mvt",{hitType:["mvtesting"]});a.sendHit(null,[["hitType",["mvtesting"]]])}};window.ATInternet.Tracker.addPlugin("MvTesting");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.OnSiteAds=function(a){var b="",h=function(c){var b=c.name;a.exec("Utils","manageChapters",[c,"chapter",3],function(a){b=a+(b?b:"")});return b},f=function(a,c){return a[c]?a[c]:""},l=function(a,c){var b=f(a,c);if(b){var d=f(a,"prefix");if(b.campaignId){var d=d||"PUB",e=f(b,"campaignId"),g=f(b,"creation"),k=f(b,"variant"),l=f(b,"format"),h=f(b,"generalPlacement"),u=f(b,"detailedPlacement"),C=f(b,"advertiserId"),b=f(b,"url");return d+"-"+e+"-"+g+"-"+k+"-"+l+"-"+h+"-"+
u+"-"+C+"-"+b}if(b.adId)return d=d||"INT",e=f(b,"adId"),g=f(b,"format"),b=f(b,"productId"),d+"-"+e+"-"+g+"||"+b}},k=function(c){var b=a.getContext("page")||{};a.sendHit({atc:l(c,"click"),type:"AT",patc:h(b),s2atc:b.level2||"",stc:c.customObject||""},[["hitType",["onSiteAdsClick"]]])},g=function(c){a.sendHit({ati:l(c,"impression"),type:"AT",stc:c.customObject||""},[["hitType",["onSiteAdsImpression"]]])},d=function(c,b){var d=a.buffer.get("ati",!0)||{};d.value="string"===typeof d.value?[d.value]:d.value||
[];d.options=d.options||{hitType:[b,"page"]};d.value.push(c);a.buffer.set("ati",d.value,d.options)},c=function(c,b){c.click?a.setParam("atc",l(c,"click"),{hitType:[b,"page"]}):c.impression&&a.setParam("ati",l(c,"impression"),{hitType:[b,"page"]});if(c.customObject){a.setContext("onsiteads",{customObject:c.customObject});var d=a.getContext("page")||{};d.customObject=ATInternet.Utils.completeFstLevelObj(d.customObject,c.customObject,!1);a.setContext("page",d)}a.dispatchSubscribe("onSiteAds")};a.selfPromotion=
this.selfPromotion={};a.publisher=this.publisher={};a.publisher.set=this.publisher.set=function(b){c(b,"publisher");a.debug("OnSiteAds:publisher:set","DEBUG","method ended",b)};a.selfPromotion.set=this.selfPromotion.set=function(b){c(b,"selfPromotion");a.debug("OnSiteAds:selfPromotion:set","DEBUG","method ended",b)};a.publisher.add=this.publisher.add=function(c){d(l(c,"impression"),"publisher");a.dispatchSubscribe("onSiteAds");a.debug("OnSiteAds:publisher:add","DEBUG","method ended",c)};a.selfPromotion.add=
this.selfPromotion.add=function(c){d(l(c,"impression"),"selfPromotion");a.dispatchSubscribe("onSiteAds");a.debug("OnSiteAds:selfPromotion:add","DEBUG","method ended",c)};var e=this.advertEvent=function(c){var b=!0;a.exec("TechClicks","manageClick",[c.elem],function(a){b=a});c.click?k(c):c.impression&&g(c);return b};a.publisher.send=this.publisher.send=function(c){a.debug("OnSiteAds:publisher:send","DEBUG","method started",c);return e(c)};a.selfPromotion.send=this.selfPromotion.send=function(c){a.debug("OnSiteAds:selfPromotion:send",
"DEBUG","method started",c);return e(c)};a.onSiteAds={};a.onSiteAds.onDispatch=this.onDispatch=function(){if(!a.dispatchSubscribed("page")){var c=a.getContext("page")||{};a.setParam("type","AT",{hitType:["publisher","selfPromotion"]});a.getParam("atc")&&(a.setParam("patc",h(c),{hitType:["publisher","selfPromotion"]}),a.setParam("s2atc",c.level2||"",{hitType:["publisher","selfPromotion"]}));(c=a.getContext("onsiteads"))&&c.customObject&&a.setParam("stc",c.customObject,{encode:!0,hitType:["publisher",
"selfPromotion"]});a.sendHit(null,[["hitType",["publisher","selfPromotion"]]])}};a.plugins.waitForDependencies(["Utils","TechClicks"],function(){b=document.location.href;a.plugins.exec("Utils","getQueryStringValue",["xtatc",b],function(c){c&&a.setParam("atc",c,{hitType:["publisher","selfPromotion","page"]})});a.emit("OnSiteAds:Ready",{lvl:"INFO",details:{href:b}})})};window.ATInternet.Tracker.addPlugin("OnSiteAds");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Page=function(a){var b=["pageId","chapterLabel","update"],h=["pid","pchap","pidt"],f=["page","site"],l=["f","x"],k=function(c){var b=c.name;a.exec("Utils","manageChapters",[c,"chapter",3],function(a){b=a+(b?b:"")});return b},g=function(a,c,b){c?a=c:a||"undefined"===typeof b||(a=b);return a},d=function(a,c,b){c.hasOwnProperty(b)&&(a[b]=g(a[b],c[b]))},c=function(c){if(!ATInternet.Utils.isPreview()||a.getConfig("preview"))ATInternet.Utils.isPrerender(function(a){c(a)})||
c()},e=function(c,b,d){if(b)for(var e=0;e<f.length;e++)if(b.hasOwnProperty(f[e])&&b[f[e]])for(var g in b[f[e]])b[f[e]].hasOwnProperty(g)&&(d?c[l[e]+g]=b[f[e]][g]:a.setParam(l[e]+g,b[f[e]][g]))},n=function(c,d,e){if(d){a.exec("Utils","manageChapters",[d,"chapter",3],function(a){a&&(d.chapterLabel=a.replace(/::$/gi,""))});for(var f=0;f<h.length;f++)d.hasOwnProperty(b[f])&&(e?c[h[f]]=d[b[f]]:a.setParam(h[f],d[b[f]]))}},p=function(c,b,d){if(b&&b.keywords instanceof Array){var e=b.keywords.length;if(0<
e){for(var f="",g=0;g<e;g++)f+="["+b.keywords[g]+"]"+(g<e-1?"|":"");d?c.tag=f:a.setParam("tag",f)}}},t=function(c,b,d){if(b){var e,f=function(a){return a?a:"0"};e=""+(f(b.category1)+"-");e+=f(b.category2)+"-";e+=f(b.category3);d?c.ptype=e:a.setParam("ptype",e)}},r=function(c,b,d){if(b)for(var e in b)b.hasOwnProperty(e)&&"undefined"!==typeof b[e]&&(d?c[e]=b[e]:a.setParam(e,b[e]))};a.customVars=this.customVars={};a.customVars.set=this.customVars.set=function(c){var b=a.getContext("page")||{},d=b.customVars;
if(d){if(c)for(var e in c)c.hasOwnProperty(e)&&(d[e]=ATInternet.Utils.completeFstLevelObj(d[e],c[e],!0))}else d=c;b.customVars=d;a.setContext("page",b);a.debug("Page:customVars:set","DEBUG","method ended",c)};a.dynamicLabel=this.dynamicLabel={};a.dynamicLabel.set=this.dynamicLabel.set=function(c){var b=a.getContext("page")||{};b.dynamicLabel=ATInternet.Utils.completeFstLevelObj(b.dynamicLabel,c,!0);a.setContext("page",b);a.debug("Page:dynamicLabel:set","DEBUG","method ended",c)};a.tags=this.tags=
{};a.tags.set=this.tags.set=function(c){var b=a.getContext("page")||{};b.tags=ATInternet.Utils.completeFstLevelObj(b.tags,c,!0);a.setContext("page",b);a.debug("Page:tags:set","DEBUG","method ended",c)};a.customTreeStructure=this.customTreeStructure={};a.customTreeStructure.set=this.customTreeStructure.set=function(c){var b=a.getContext("page")||{};b.customTreeStructure=ATInternet.Utils.completeFstLevelObj(b.customTreeStructure,c,!0);a.setContext("page",b);a.debug("Page:customTreeStructure:set","DEBUG",
"method ended",c)};a.page={};a.page.reset=this.reset=function(){a.setContext("page",void 0);a.debug("Page:page:reset","DEBUG","method ended")};a.page.set=this.set=function(c){a.dispatchSubscribe("page");var b=a.getContext("page")||{};b.name=g(b.name,c.name,"");b.level2=g(b.level2,c.level2,"");d(b,c,"chapter1");d(b,c,"chapter2");d(b,c,"chapter3");b.customObject=ATInternet.Utils.completeFstLevelObj(b.customObject,c.customObject,!0);a.setContext("page",b);a.debug("Page:page:set","DEBUG","method ended",
c)};a.page.send=this.send=function(b){var f={p:k(b),s2:b.level2||""},l=!0,h=b.customObject;if(h){var s=a.getParam("stc",!0);if(s&&s.options.permanent){var u=s?s.options.hitType:[],C=ATInternet.Utils.arrayIndexOf;if(-1!=C(u,"page")||-1!=C(u,"all"))h=ATInternet.Utils.completeFstLevelObj(s.value||{},h,!0)}a.exec("Utils","customObjectToString",[h],function(a){f.stc=a})}h=a.getContext("page")||{};h.vrn&&(f.vrn=h.vrn,h.vrn=void 0,a.setContext("page",h));s=a.getContext("InternalSearch")||{};"undefined"!=
typeof s.keyword&&(f.mc=ATInternet.Utils.cloneSimpleObject(s.keyword),"undefined"!=typeof s.resultPageNumber&&(f.np=ATInternet.Utils.cloneSimpleObject(s.resultPageNumber)),a.setContext("InternalSearch",void 0));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&(f.pvw=1);e(f,b.customVars,!0);n(f,b.dynamicLabel,!0);p(f,b.tags,!0);t(f,b.customTreeStructure,!0);s=a.getContext("campaigns")||{};r(f,s,!0);a.setContext("campaigns",void 0);a.exec("TechClicks","manageClick",[b.elem],function(a){l=a});c(function(){a.sendHit(f)});
h.name=g(h.name,b.name,"");h.level2=g(h.level2,b.level2,"");d(h,b,"chapter1");d(h,b,"chapter2");d(h,b,"chapter3");a.setContext("page",h);a.debug("Page:page:send","DEBUG","method ended",b);return l};a.page.onDispatch=this.onDispatch=function(){var b=a.getContext("page")||{},d=a.getContext("InternalSearch")||{};a.setParam("p",k(b));a.setParam("s2",b.level2||"");b.vrn&&(a.setParam("vrn",b.vrn),b.vrn=void 0,a.setContext("page",b));"undefined"!=typeof d.keyword&&(a.setParam("mc",ATInternet.Utils.cloneSimpleObject(d.keyword)),
"undefined"!=typeof d.resultPageNumber&&a.setParam("np",ATInternet.Utils.cloneSimpleObject(d.resultPageNumber)),a.setContext("InternalSearch",void 0));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&a.setParam("pvw",1);e(null,b.customVars,!1);n(null,b.dynamicLabel,!1);p(null,b.tags,!1);t(null,b.customTreeStructure,!1);d=a.getContext("campaigns")||{};r(null,d,!1);a.setContext("campaigns",void 0);var b=b.customObject,f=[["hitType",["page"]]];if(b)if(d=a.getParam("stc",!0)){var g=d.options.hitType||
[],h=ATInternet.Utils.arrayIndexOf,h=-1!=h(g,"page")||-1!=h(g,"all"),g=d.options.permanent;h?(h=ATInternet.Utils.cloneSimpleObject(d),h.value=ATInternet.Utils.completeFstLevelObj(h.value||{},b,!0),a.setParam("stc",h.value,{encode:!0}),c(function(){a.sendHit(null,f)}),g&&a.setParam("stc",d.value,d.options)):(a.setParam("stc",b,{encode:!0}),c(function(){a.sendHit(null,f)}),a.setParam("stc",d.value,d.options))}else a.setParam("stc",b,{encode:!0}),c(function(){a.sendHit(null,f)});else c(function(){a.sendHit(null,
f)})}};window.ATInternet.Tracker.addPlugin("Page");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.SalesTracker=function(a){var b=function(b,c,e){b.hasOwnProperty(e)&&(b=b[e],a.setParam(c,void 0===b?"":b+"",{hitType:["page"]}))},h=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},f=function(a){return"object"===typeof a&&!(a instanceof Array)},l=function(b){var c="";a.exec("Utils","manageChapters",[b,"category",6],function(a){a&&(c=a)});c+=b.productId;b=a.getContext("product")||{};b.viewedProducts?b.viewedProducts.push(c):b.viewedProducts=[c];
a.setContext("product",b)},k=0,g=function(b){var c=b.productId?b.productId:"",e=b.category?b.category+"::":"";a.exec("Utils","manageChapters",[b,"category",6],function(a){a&&(e=a)});return e+c};a.order=this.order={};a.cart=this.cart={};a.aisle=this.aisle={};a.salesTracker={};a.product=this.product={};a.order.set=this.order.set=function(d){var c=!1;if(f(d)&&!h(d)){c=!0;a.dispatchSubscribe("page");a.dispatchSubscribe("salesTracker");b(d,"cmd","orderId");b(d,"roimt","turnover");b(d,"st","status");"boolean"===
typeof d.newCustomer?a.setParam("newcus",d.newCustomer?"1":"0",{hitType:["page"]}):d.newCustomer&&(a.debug("SalesTracker:order:set:newCustomer:Error","ERROR","Not a boolean",d),"undefined"===typeof a.getParams("newcus")&&a.setParam("newcus","0",{hitType:["page"]}));var e=d.amount;f(e)?(b(e,"mtht","amountTaxFree"),b(e,"mtttc","amountTaxIncluded"),b(e,"tax","taxAmount")):e&&a.debug("SalesTracker:order:set:amount:Error","ERROR","Not an object",{value:e});e=d.delivery;f(e)?(b(e,"fp","shippingFeesTaxIncluded"),
b(e,"fpht","shippingFeesTaxFree"),b(e,"dl","deliveryMethod")):e&&a.debug("SalesTracker:order:set:delivery:Error","ERROR","Not an object",{value:e});b(d,"mp","paymentMethod");e=d.discount;f(e)?(b(e,"dsc","discountTaxIncluded"),b(e,"dscht","discountTaxFree"),b(e,"pcd","promotionalCode")):e&&a.debug("SalesTracker:order:set:discount:Error","ERROR","Not an object",{value:e});"boolean"===typeof d.confirmationRequired?a.setParam("tp",d.confirmationRequired?"pre1":"",{hitType:["page"]}):d.confirmationRequired&&
(a.debug("SalesTracker:order:set:confirmationRequired:Error","ERROR","Not a boolean",d),"undefined"===typeof a.getParams("tp")&&a.setParam("tp","",{hitType:["page"]}));e=d.orderCustomVariables;if(e instanceof Array)for(var g=0;g<e.length;g++)b(e,"o"+(g+1),g);else e&&a.debug("SalesTracker:order:set:orderCustomVariables:Error","ERROR","Not an array",{value:e})}a.debug("SalesTracker:order:set","DEBUG","method ended",d);return c};a.cart.set=this.cart.set=function(d){var c=!1;f(d)&&!h(d)&&(c=!0,a.dispatchSubscribe("page"),
a.dispatchSubscribe("salesTracker"),b(d,"idcart","cartId"),"boolean"===typeof d.isBasketPage?"pre1"!==a.getParams("tp")&&a.setParam("tp",d.isBasketPage?"cart":"",{hitType:["page"]}):d.isBasketPage&&(a.debug("SalesTracker:cart:set:isBasketPage:Error","ERROR","Not a boolean",d),"undefined"===typeof a.getParams("tp")&&a.setParam("tp","",{hitType:["page"]})));a.debug("SalesTracker:cart:set","DEBUG","method ended",d);return c};a.cart.add=this.cart.add=function(d){var c=!1;if(f(d)&&!h(d)){var c=!0,e=d.product;
if(f(e)){k++;var l=k,p=g(e);a.setParam("pdt"+l,p,{hitType:["page"]});b(e,"qte"+l,"quantity");b(e,"mt"+l,"unitPriceTaxIncluded");b(e,"mtht"+l,"unitPriceTaxFree");b(e,"dsc"+l,"discountTaxIncluded");b(e,"dscht"+l,"discountTaxFree");b(e,"pcode"+l,"promotionalCode")}else e&&a.debug("SalesTracker:cart:add:product:Error","ERROR","Not an object",{value:e})}a.debug("SalesTracker:cart:add","DEBUG","method ended",d);return c};a.aisle.set=this.aisle.set=function(b){var c=!1;if(f(b)&&!h(b)){c=!0;a.dispatchSubscribe("page");
var e="";a.exec("Utils","manageChapters",[b,"level",6],function(a){e=a});e=e.replace(/::$/gi,"");a.setParam("aisl",e,{hitType:["page"]})}a.debug("SalesTracker:aisle:set","DEBUG","method ended",b);return c};a.product.add=this.product.add=function(b){var c=!1,e;if(e=f(b))if(e=!h(b)){a:{e=["productId"];for(var g=0;g<e.length;g++)if(void 0===b[e[g]]){e=!0;break a}e=!1}e=!e}e?(c=!0,l(b),a.dispatchSubscribe("salesTracker")):a.debug("SalesTracker:product:add:Error","ERROR","Product object content problem",
b);a.debug("SalesTracker:product:add","DEBUG","method ended",b);return c};a.salesTracker.onDispatch=this.onDispatch=function(){""===a.getParams("cmd")&&a.debug("SalesTracker:order:onDispatch:Error","ERROR",'Required "orderId" parameter is not defined');a.getParams("idcart")||"cart"!==a.getParams("tp")&&"pre1"!==a.getParams("tp")||a.debug("SalesTracker:cart:onDispatch:Error","ERROR",'Required "cartId" parameter is not defined');var b=a.getContext("product");b&&b.viewedProducts&&0<b.viewedProducts.length&&
(a.setParam("pdtl",b.viewedProducts.join("|"),{hitType:["product"]}),a.setParam("type","pdt",{hitType:["product"]}),a.sendHit(null,[["hitType",["product"]]]))}};window.ATInternet.Tracker.addPlugin("SalesTracker");
}).call(window);;(function(){var dfltPluginCfg={"clicksAutoManagementEnabled":true,"clicksAutoManagementTimeout":500};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.TechClicks=function(a){var b,h;a.configPlugin("TechClicks",dfltPluginCfg||{},function(a){b=a.clicksAutoManagementEnabled;h=a.clicksAutoManagementTimeout});this.deactivateAutoManagement=function(){b=!1};var f=function(a){switch(a.target){case "_top":window.top.location.href=a.url;break;case "_parent":window.parent.location.href=a.url;break;default:window.location.href=a.url}},l=function(a){var c=a.timeout;a.mailto?setTimeout(function(){window.location.href=a.mailto},
c):a.form?setTimeout(function(){a.form.submit()},c):a.url&&setTimeout(function(){f({url:a.url,target:a.target})},c)},k=function(c){for(var b,d="_self",g=c.timeoutonly;c;){if(c.href&&0===c.href.indexOf("http")){b=c.href.split('"').join('\\"');d=c.target?c.target:d;break}c=c.parentNode}if(b){if(!g)a.onTrigger("Tracker:Hit:Sent:Ok",function(){f({url:b,target:d})});l({url:b,target:d,timeout:h})}},g=function(c){var b=c;for(c=b.timeoutonly;b&&"FORM"!==b.nodeName;)b=b.parentNode;if(b){if(!c)a.onTrigger("Tracker:Hit:Sent:Ok",
function(){b.submit()});l({form:b,timeout:h})}},d=function(c){var b=c;for(c=b.timeoutonly;b&&!(b.href&&0<=b.href.indexOf("mailto:"));)b=b.parentNode;if(b){if(!c)a.onTrigger("Tracker:Hit:Sent:Ok",function(){window.location.href=b.href});l({mailto:b.href,timeout:h})}},c=function(a){for(;a;){if(a.href){if(0<=a.href.indexOf("mailto:"))return"mailto";if(0===a.href.indexOf("http"))return"redirection"}else if("FORM"===a.nodeName)return"form";a=a.parentNode}return!1};this.manageClick=function(a,f){if(b&&
a){var l;a:{for(l=a;l;){if("function"===typeof l.getAttribute&&("_blank"===l.getAttribute("target")||"no"===l.getAttribute("data-atclickmanagement"))){l=!0;break a}l=l.parentNode}l=a;for(var h=window.location.href,r;l;){if((r=l.href)&&0<r.indexOf("#")&&h.substring(0,0<h.indexOf("#")?h.indexOf("#"):h.length)===r.substring(0,r.indexOf("#"))){l=!0;break a}l=l.parentNode}l=!1}h=c(a);if(!l&&h){switch(h){case "mailto":d(a);break;case "form":g(a);break;case "redirection":k(a);break;default:return!0}f&&!f.defaultPrevented&&
f.preventDefault();return!1}}return!0}};window.ATInternet.Tracker.addPlugin("TechClicks");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Utils=function(a){var b=this,h={};b.getQueryStringValue=function(a,b){var f=window.ATInternet.Utils.hashcode(b).toString();if(!h[f]){h[f]={};var d=RegExp("[&#?]{1}([^&=#?]*)=([^&#]*)?","g"),c=d.exec(b);if(null!==c)for(;null!==c;)h[f][c[1]]=c[2],c=d.exec(b)}return h[f].hasOwnProperty(a)?h[f][a]:null};b.customObjectToString=function(a){return encodeURIComponent(window.ATInternet.Utils.jsonSerialize(a))};b.manageChapters=function(b,f,g){var d=a.getConfig("ignoreEmptyChapterValue"),
c="";if(b){g=parseInt(g,10);for(var e=1;e<g+1;e++)var n=b[f+e]||"",c=d?c+(n?n+"::":""):c+(b.hasOwnProperty(f+e)?n+"::":"")}return c};b.getDocumentLevel=function(){var b=a.getConfig("documentLevel");if(0>b.indexOf("."))return window[b]||document;b=b.split(".");return window[b[0]][b[1]]||document};b.getLocation=function(){return b.getDocumentLevel().location.href};a.dispatchIndex={};a.dispatchStack=[];a.dispatchEventFor={};var f=0;a.dispatchSubscribe=function(b){return a.dispatchIndex[b]?!1:(a.dispatchStack.push(b),
a.dispatchIndex[b]=!0)};a.dispatchSubscribed=function(b){return!0===a.dispatchIndex[b]};a.addSpecificDispatchEventFor=function(b){return a.dispatchEventFor[b]?!1:(a.dispatchEventFor[b]=!0,f++,!0)};a.processSpecificDispatchEventFor=function(b){a.dispatchEventFor[b]&&(a.dispatchEventFor[b]=!1,f--,0===f&&(a.dispatchEventFor={},a.emit("Tracker:Plugin:SpecificEvent:Exec:Complete",{lvl:"INFO"})))};a.dispatch=function(){var b=function(){for(;0<a.dispatchStack.length;){var b=a.dispatchStack.pop();a[b].onDispatch()}a.dispatchIndex=
{};a.delContext(void 0,"customObject");a.debug("Utils:dispatch","DEBUG","method ended")},k=function(){if(a.plugins.isExecWaitingLazyloading())a.onTrigger("Tracker:Plugin:Lazyload:Exec:Complete",function(){b()},!0);else b()};if(0===f)k();else a.onTrigger("Tracker:Plugin:SpecificEvent:Exec:Complete",function(){k()},!0)};a.dispatchRedirect=function(b){var f=!0;b&&b.elem&&(b.elem.timeoutonly=!0,a.plugins.exec("TechClicks","manageClick",[b.elem],function(a){f=a}));a.dispatch();return f}};window.ATInternet.Tracker.addPlugin("Utils");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.RichMedia=function(a){var b=new function(){this._timeout={};this.setTimeout=function(b,c,e){this._timeout[b]=this._timeout[b]||{};this._timeout[b][c]=window.setTimeout(function(){a.richMedia.send({action:"refresh",playerId:b,mediaLabel:c})},1E3*e)};this.setTimeoutObject=function(b,c,e){this._timeout[b]=this._timeout[b]||{};if("undefined"===typeof this._timeout[b][c]){var f=[],k;for(k in e)e.hasOwnProperty(k)&&f.push({delay:g(k,0),refresh:g(e[k],5)});f.sort(function(a,
b){return a.delay<b.delay?-1:a.delay>b.delay?1:0});this._timeout[b][c]={arrObj:f}}e=this._timeout[b][c];if(0<e.arrObj.length&&(f=e.arrObj[0].delay,k=e.arrObj[0].refresh,"number"===typeof f&&"number"===typeof k&&0<k)){e[f]=e[f]||{};var h=void 0;"undefined"!==typeof e.arrObj[1]&&(h=e.arrObj[1].delay);var l=0;"undefined"===typeof h?l=1:"number"===typeof e[f].num?l=Math.max(e[f].num-1,0):"number"===typeof h&&(l=Math.floor(60*(h-f)/k));e[f].num=l;0<l?e[f].timeout=window.setTimeout(function(){a.richMedia.send({action:"refresh",
playerId:b,mediaLabel:c})},1E3*k):"undefined"!==typeof e[f].timeout&&(window.clearTimeout(e[f].timeout),e[f].timeout=void 0,e.arrObj.splice(0,1),window.setTimeout(function(){a.richMedia.send({action:"refresh",playerId:b,mediaLabel:c})},1E3*k));this._timeout[b][c]=e}};this.clearTimeout=function(a,b){this._timeout[a]=this._timeout[a]||{};if("object"===typeof this._timeout[a][b])for(var e in this._timeout[a][b]){if(this._timeout[a][b].hasOwnProperty(e)){var f=this._timeout[a][b][e].num;"undefined"!==
typeof f&&0<f&&(window.clearTimeout(this._timeout[a][b][e].timeout),this._timeout[a][b][e].timeout=void 0)}}else window.clearTimeout(this._timeout[a][b])};this.removePlayer=function(b){for(var c in this._timeout[b])this._timeout[b].hasOwnProperty(c)&&(this.clearTimeout(b,c),a.richMedia.send({action:"stop",playerId:b,mediaLabel:c}));this._timeout[b]={}};this.removeAll=function(){for(var a in this._timeout)this._timeout.hasOwnProperty(a)&&this.removePlayer(a);this._timeout={}}},h=new function(){this._media=
function(){this.m9=this.m6=this.m5=this.m1=this.rfsh=this.buf=this.a=this.p=this.clnk=this.s2=this.plyr=this.type=""};this._mediaAll={};this.setMediaProperty=function(a,b,e,f){this._mediaAll[a]=this._mediaAll[a]||{};this._mediaAll[a][b]=this._mediaAll[a][b]||new this._media;this._mediaAll[a][b][e]=f};this.getMediaProperty=function(a,b,e){return this._mediaAll[a]&&this._mediaAll[a][b]?this._mediaAll[a][b][e]:""};this.removePlayer=function(a){this._mediaAll[a]={}};this.removeAll=function(){this._mediaAll=
{}}},f=function(b,c,e){var f=b[e]||"";a.exec("Utils","manageChapters",[b,c,3],function(a){f=a+f});return f},l=function(b,c,e,f){"boolean"===typeof b[c]?b[c]&&(e=f):b[c]&&a.debug("RichMedia:richmedia:"+c+":Error","ERROR","Not a boolean",{value:b[c]});return e},k=function(b){var c=0;/^(\-|\+)?([0-9]+)$/.test(b)?c=Number(b):b&&a.debug("RichMedia:richMedia:playerId:Error","ERROR","Not an integer",{value:b});return c},g=function(a,b){var e=parseInt(a,10);return e?Math.max(e,b):0};a.richMedia={};a.richMedia.add=
this.add=function(b){b=b||{};var c=k(b.playerId),e=f(b,"mediaTheme","mediaLabel"),g=l(b,"isBuffering","0","1"),p=l(b,"isEmbedded","int","ext");h.setMediaProperty(c,e,"plyr",c);h.setMediaProperty(c,e,"type",b.mediaType||"");h.setMediaProperty(c,e,"s2",b.mediaLevel2||"");h.setMediaProperty(c,e,"p",e);h.setMediaProperty(c,e,"clnk",b.previousMedia||"");h.setMediaProperty(c,e,"a",b.action||"");h.setMediaProperty(c,e,"buf",g);h.setMediaProperty(c,e,"rfsh",b.refreshDuration||"");h.setMediaProperty(c,e,"m1",
b.duration||"");h.setMediaProperty(c,e,"m5",p);h.setMediaProperty(c,e,"m6",b.broadcastMode||"");h.setMediaProperty(c,e,"m9",b.webdomain||"");a.debug("RichMedia:richMedia:add","DEBUG","method ended",{player:c,media:h,tagData:b})};a.richMedia.remove=this.remove=function(d){b.removePlayer(d);h.removePlayer(d);a.debug("RichMedia:richMedia:remove","DEBUG","method ended",{playerId:d,media:h})};a.richMedia.removeAll=this.removeAll=function(){b.removeAll();h.removeAll();a.debug("RichMedia:richMedia:removeAll",
"DEBUG","method ended",{media:h})};a.richMedia.send=this.send=function(d){d=d||{};var c=k(d.playerId),e=f(d,"mediaTheme","mediaLabel"),n={},p=l(d,"isBuffering","0","1");n.type=h.getMediaProperty(c,e,"type");n.plyr=c;n.p=e;n.a=d.action||"";n.s2=h.getMediaProperty(c,e,"s2");n.m1=h.getMediaProperty(c,e,"m1");n.m5=h.getMediaProperty(c,e,"m5");n.m6=h.getMediaProperty(c,e,"m6");(""===n.type||""===n.m6||"clip"===n.m6&&""===n.m1)&&a.debug("RichMedia:richMedia:send:Error","WARNING",'Some required parameters are missing, please use "tag.richMedia.add()" method to set',
{mediaType:n.type,broadcastMode:n.m6,duration:n.m1});if("play"===n.a||"info"===n.a)n.buf=p,p=a.getContext("page")||{},n.prich=f(p,"chapter","name"),n.s2rich=p.level2||"",n.clnk=h.getMediaProperty(c,e,"clnk"),n.m9=encodeURIComponent(h.getMediaProperty(c,e,"m9"));a.sendHit(n,[["hitType",["richmedia"]]]);"pause"!==n.a&&"stop"!==n.a||b.clearTimeout(c,e);if("play"===n.a||"refresh"===n.a)p=h.getMediaProperty(c,e,"rfsh"),"object"===typeof p?b.setTimeoutObject(c,e,p):(p=g(p,5),0!==p&&b.setTimeout(c,e,p));
a.debug("RichMedia:richMedia:send","DEBUG","method ended",{player:c,media:h,buffer:n,tagData:d})}};window.ATInternet.Tracker.addPlugin("RichMedia");
}).call(window);if(typeof window.ATInternet.onTrackerLoad==='function'){window.ATInternet.onTrackerLoad();}